version: 2.1

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi
jobs:
  checkout_code:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build

  bundle_dependencies:
    docker:
      - image: circleci/clojure:lein-2.8.3-node
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-node-dependencies-{{ checksum "package.json" }}
      - run: lein modules :dirs workivabuild/prefetch-deps deps
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - save_cache:
          key: v1-node-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/node_modules

  lint_code:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "project.clj" }}
      - run: rm -rf ./workivabuild/prefetch-deps
      - run: lein modules cljfmt check

  verify_license_headers:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "project.clj" }}
      - run: ./.circleci/scripts/verify-license-headers.sh "clj" "^;; Copyright 2018-[0-9]{4} Workiva Inc.$" project.clj profiles.clj
      - run: ./.circleci/scripts/verify-license-headers.sh "java" "^// Copyright 2018-[0-9]{4} Workiva Inc.$"

  build_and_test_and_verify_docs:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-node-dependencies-{{ checksum "package.json" }}
      # Install / Test
      - run: rm -rf ./workivabuild/prefetch-deps
      - run: lein modules do test, install
      - run: lein modules :dirs server.alpha uberjar
      - run: mkdir -p ./artifacts/jars
      - run: mv ./**/target/*.jar ./artifacts/jars/
      # Persist Server JAR
      - run: cp ./artifacts/jars/server.alpha*.jar /tmp/server.alpha.jar
      # Verify Docs
      - run: ./.circleci/scripts/verify-docs.sh
      - run: cd ./documentation && tar cvfz "../eva-catalog-docs.tgz" ./
      - run: mkdir -p ./artifacts/docs
      - run: mv ./eva-catalog-docs.tgz ./artifacts/docs/
      - store_artifacts:
          path: ./artifacts
      - persist_to_workspace:
          root: /tmp
          paths:
            - server.alpha.jar

  # Verify that internal CI system will not fail after a merged PR
  verify_docker_build:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          docker_layer_caching: false
      - run: ./.circleci/scripts/verify-dockerfile.sh

  deploy_clojars:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - early_return_for_forked_pull_requests
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "project.clj" }}
      - run: mkdir -p ~/.lein
      - run: cp ./.circleci/clojars/profiles.clj ~/.lein/profiles.clj
      - run: lein modules :dirs "common.alpha:client.alpha" deploy clojars

  build_and_push_docker_image:
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          docker_layer_caching: false
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir -p ./server.alpha/target/
      - run: mv /tmp/workspace/server.alpha.jar ./server.alpha/target/server.alpha.jar
      - run: docker build -f catalog.Dockerfile -t workivadocker/eva-catalog:latest-release -t workivadocker/eva-catalog:$CIRCLE_TAG .
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - run: docker push workivadocker/eva-catalog:latest-release
      - run: docker push workivadocker/eva-catalog:$CIRCLE_TAG

workflows:
  eva_catalog_workflow:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /[0-9a-f]{7}_cr_no_smithy/
      - bundle_dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - verify_license_headers:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - verify_docker_build:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - lint_code:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: /.*/
      - build_and_test_and_verify_docs:
          requires:
            - bundle_dependencies
            - verify_license_headers
            - lint_code
          filters:
            tags:
              only: /.*/
      - deploy_clojars:
          context: Clojars
          requires:
            - build_and_test_and_verify_docs
            - verify_docker_build
          # Only run on tagged builds starting with 'v'
          # Therefore, releases MUST start with 'v'
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build_and_push_docker_image:
          context: DockerHub
          requires:
            - verify_docker_build
            - build_and_test_and_verify_docs
          # Only run on tagged builds starting with 'v'
          # Therefore, releases MUST start with 'v'
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
